<?php

namespace App\Ldap;

use App\Ldap\Traits\FromCommunityScopeTrait;
use App\Ldap\Traits\SearchScopeTrait;
use LdapRecord\Models\Model;
use LdapRecord\Models\OpenLDAP\OrganizationalUnit;

class Committee extends OrganizationalUnit
{
    use FromCommunityScopeTrait;

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}
