<?php

namespace App\Ldap;

use App\Ldap\Traits\FromCommunityScopeTrait;
use App\Ldap\Traits\SearchScopeTrait;

class Group extends \LdapRecord\Models\OpenLDAP\Group
{
    use FromCommunityScopeTrait;
    use SearchScopeTrait;

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

    public static function dnFrom(string $uid, string $cn){
        return "cn=$cn," . self::dnRoot($uid);
    }

    public static function dnRoot(string $uid){
        return "ou=Groups,ou=$uid,ou=Communities," . config('ldap.connections.default.base_dn');
    }

    public function setDnFrom(string $uid, string $cn): static
    {
        $dn = self::dnFrom($uid, $cn);
        return parent::setDn($dn);
    }

}
